plugins {
    id 'java'
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'dev.oakheart'
version = '2.0.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "coreprotect-repo"
        url = "https://maven.playpro.com"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io"
    }
    maven {
        name = "nexo-repo"
        url = "https://repo.nexomc.com/releases"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT")
    compileOnly("net.coreprotect:coreprotect:22.4")
    compileOnly("com.github.LoneDev6:api-itemsadder:3.6.3-beta-14")
    compileOnly("com.nexomc:nexo:0.1.0")
    compileOnly(files("libs/VulcanAPI.jar"))
    implementation("org.bstats:bstats-bukkit:3.1.0")
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

compileJava {
    options.encoding = 'UTF-8'
    options.release = 21
    options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching(['plugin.yml', 'paper-plugin.yml']) {
        expand props
    }
}

shadowJar {
    relocate 'org.bstats', 'dev.oakheart.oaktools.bstats'
    archiveClassifier.set('')
}

build.dependsOn shadowJar
