name: OakTools
version: '${version}'
main: dev.oakheart.oaktools.OakTools
description: 'Player-friendly building utilities for survival.'
api-version: '1.21.8'
authors:
  - Loralon
website: https://github.com/LoralonMC/OakTools
dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CoreProtect:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: false
    OakOverflow:
      load: BEFORE
      required: false
permissions:
  oaktools.*:
    description: 'All OakTools permissions'
    default: op
    children:
      oaktools.give: true
      oaktools.reload: true
      oaktools.info: true
      oaktools.repair: true
      oaktools.use.file: true
      oaktools.use.trowel: true
      oaktools.use.wand: true
      oaktools.craft.file: true
      oaktools.craft.trowel: true
      oaktools.craft.wand: true
      oaktools.use.excavator: true
      oaktools.use.lumberjack: true
      oaktools.use.veinminer: true
      oaktools.craft.excavator: true
      oaktools.craft.lumberjack: true
      oaktools.craft.veinminer: true
      oaktools.use.sickle: true
      oaktools.craft.sickle: true
      oaktools.repair.anvil: true
      oaktools.bypass.protection: true
  oaktools.give:
    description: 'Give tools to players'
    default: op
  oaktools.reload:
    description: 'Reload configuration'
    default: op
  oaktools.info:
    description: 'View tool information'
    default: op
  oaktools.repair:
    description: 'Repair tools via command'
    default: op
  oaktools.use.file:
    description: 'Use the File tool'
    default: true
  oaktools.use.trowel:
    description: 'Use the Trowel tool'
    default: true
  oaktools.craft.file:
    description: 'Craft the File tool'
    default: true
  oaktools.craft.trowel:
    description: 'Craft the Trowel tool'
    default: true
  oaktools.use.wand:
    description: 'Use the Builder''s Wand tool'
    default: true
  oaktools.craft.wand:
    description: 'Craft the Builder''s Wand tool'
    default: true
  oaktools.repair.anvil:
    description: 'Repair OakTools items in an anvil'
    default: true
  oaktools.use.excavator:
    description: 'Use the Excavation Shovel'
    default: true
  oaktools.use.lumberjack:
    description: "Use the Lumberjack's Axe"
    default: true
  oaktools.use.veinminer:
    description: 'Use the Vein Miner Pickaxe'
    default: true
  oaktools.craft.excavator:
    description: 'Craft the Excavation Shovel'
    default: true
  oaktools.craft.lumberjack:
    description: "Craft the Lumberjack's Axe"
    default: true
  oaktools.craft.veinminer:
    description: 'Craft the Vein Miner Pickaxe'
    default: true
  oaktools.use.sickle:
    description: 'Use the Sickle tool'
    default: true
  oaktools.craft.sickle:
    description: 'Craft the Sickle tool'
    default: true
  oaktools.bypass.protection:
    description: 'Use tools in protected regions'
    default: false
